### ISSUE TITLE
Add .exe support for Windows, MacOS, and Linux

### ISSUE THREAD

**Issue by thegithubguy909** [lucasstarsz/FastJ-Engine#5]
There's a way to do this. Use Visual Studio. Also, maybe add a built in IDE

**Comment by lucasstarsz** [comment]
For now, the game engine isn't really game-creation friendly, as it's in its development phase. Later on, features like these may be added, but right now the main focus is the core of the game engine itself. 

On that, do note that there will be a massive update coming soon, which changes pretty much everything so far about this engine (which is why it's taken so long to work on). Keep your eyes alert; it'll be out fairly soon 👍
